# Generated by Django 5.2.3 on 2025-10-05 08:52

import apps.exam_board.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문(HTML)')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('PUBLISHED', '발행')], default='DRAFT', max_length=10, verbose_name='상태')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='발행일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '시험정보 게시글',
                'verbose_name_plural': '시험정보 게시글',
                'ordering': ('-is_pinned', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='이미지, 문서, HWP/HWPX, ZIP 등 허용', max_length=255, upload_to=apps.exam_board.models.exam_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'zip', 'hwp', 'hwpx'])], verbose_name='파일')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('file', 'File')], default='file', max_length=10, verbose_name='종류')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='원본 파일명')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='파일 크기(Byte)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='콘텐츠 타입')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='설명(옵션)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬순서(옵션)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='exam_board.exampost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '첨부 파일',
                'verbose_name_plural': '첨부 파일',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='exampost',
            index=models.Index(fields=['status', '-created_at'], name='exam_board__status_d673e9_idx'),
        ),
        migrations.AddIndex(
            model_name='exampost',
            index=models.Index(fields=['-is_pinned', '-created_at'], name='exam_board__is_pinn_e4e827_idx'),
        ),
        migrations.AddIndex(
            model_name='exampost',
            index=models.Index(fields=['-created_at'], name='exam_board__created_f016bb_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['post', 'sort_order'], name='exam_board__post_id_92e3c2_idx'),
        ),
    ]
