# Generated by Django 5.2.3 on 2025-06-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exam_schedule', models.TextField(help_text='시험 일정 또는 안내')),
                ('image', models.ImageField(blank=True, help_text='자격증 상세 이미지 (선택)', null=True, upload_to='certificates/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '자격증 안내',
                'verbose_name_plural': '자격증 안내',
                'ordering': ['name'],
            },
        ),
    ]
