# Generated by Django 5.2.3 on 2025-07-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmcd', models.CharField(blank=True, help_text='Q-Net 종목코드', max_length=10, null=True)),
                ('slug', models.SlugField(help_text='URL 식별용 슬러그 (예: hansik)', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateExamPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impl_yy', models.IntegerField(help_text='시행년도')),
                ('impl_seq', models.IntegerField(help_text='시행회차')),
                ('qualgb_cd', models.CharField(choices=[('T', '국가기술자격'), ('C', '과정평가형자격'), ('W', '일학습병행자격'), ('S', '국가전문자격')], max_length=2)),
                ('qualgb_nm', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('doc_reg_start_dt', models.DateField()),
                ('doc_reg_end_dt', models.DateField()),
                ('doc_exam_start_dt', models.DateField()),
                ('doc_exam_end_dt', models.DateField()),
                ('doc_pass_dt', models.DateField()),
                ('prac_reg_start_dt', models.DateField()),
                ('prac_reg_end_dt', models.DateField()),
                ('prac_exam_start_dt', models.DateField()),
                ('prac_exam_end_dt', models.DateField()),
                ('prac_pass_dt', models.DateField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_plans', to='certificates.certificate')),
            ],
            options={
                'ordering': ['impl_yy', 'impl_seq'],
            },
        ),
    ]
