# Generated by Django 5.2.3 on 2025-06-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.TextField(verbose_name='대표 인사말')),
                ('vision', models.TextField(verbose_name='학원 비전')),
                ('address', models.CharField(max_length=255, verbose_name='학원 찾아오는 길')),
                ('phone', models.CharField(max_length=50, verbose_name='대표 번호')),
                ('opening_hours', models.CharField(max_length=100, verbose_name='운영 시간')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/%Y/%m/%d/', verbose_name='대표 이미지')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일시')),
            ],
            options={
                'verbose_name': '학원 소개',
                'verbose_name_plural': '학원 소개',
            },
        ),
    ]
