# Generated by Django 5.2.3 on 2025-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopupBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='배너 제목')),
                ('image', models.ImageField(help_text='팝업에 표시될 이미지', upload_to='popup/%Y/%m/%d/', verbose_name='팝업 이미지')),
                ('link_url', models.URLField(blank=True, help_text='배너 클릭 시 이동할 URL', null=True, verbose_name='링크 URL')),
                ('is_active', models.BooleanField(default=False, help_text='True인 배너만 화면에 표시 (단일 활성)', verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '팝업 배너',
                'verbose_name_plural': '팝업 배너',
                'ordering': ['-created_at'],
            },
        ),
    ]
