# Generated by Django 5.2.3 on 2025-06-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='이미지 제목')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='갤러리 이미지 파일')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='간단 설명')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
            ],
            options={
                'verbose_name': '갤러리 이미지',
                'verbose_name_plural': '갤러리 이미지',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
