# Generated by Django 5.2.3 on 2025-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('academy', '학원 강의'), ('hrd', 'HRD-Net 강의')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lectures/')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day_of_week', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('applied', models.PositiveIntegerField(default=0)),
                ('process_id', models.CharField(blank=True, max_length=100, null=True)),
                ('apply_url', models.URLField(blank=True, max_length=500, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
