name: Backend CI
on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: ci
      DEBUG: "False"
      DATABASE_URL: "sqlite:///./ci.sqlite3" # CI는 sqlite 사용
      SECRET_KEY: "ci-secret"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -c "import pkgutil; print('drf_spectacular:', bool(pkgutil.find_loader('drf_spectacular'))); print('drf_spectacular_sidecar:', bool(pkgutil.find_loader('drf_spectacular_sidecar')))"

      - name: Django deploy checks
        run: python manage.py check --deploy

      - name: Collect static
        run: python manage.py collectstatic --noinput
