name: Backend CI
on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: ci
      DEBUG: "False"
      # CI는 sqlite로 테스트 (Neon 연결 불필요)
      DATABASE_URL: "sqlite:///./ci.sqlite3"
      SECRET_KEY: "ci-secret"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: python manage.py check --deploy
      - run: python manage.py collectstatic --noinput
      # 유닛테스트가 있으면 활성화
      # - run: pytest -q
